import React from 'react';
import Svg,{Path} from 'react-native-svg';
import {View,Text,Pressable} from '../ui';
import {RecordNode} from '../logic/sgf';
import {C} from '../theme';
export const variationRoot=(node:RecordNode)=>{let root:RecordNode|null=null;for(let n=node;n.parent;n=n.parent)if(n.parent.children[0]!==n)root=n;return root;};
export default function RecordControls({node,onNode,onNav,commentVisible,onComment}:{node:RecordNode;onNode:(n:RecordNode)=>void;onNav:(a:'start'|'prev'|'next'|'end')=>void;commentVisible:boolean;onComment:()=>void}){
 const branch=variationRoot(node);let end=node;while(end.children.length)end=end.children[0];const canToggle=!!branch||node.children.length>1;
 const icon=(label:string,path:string,fn:()=>void,disabled=false,selected=false)=><Pressable accessibilityLabel={label} onPress={fn} disabled={disabled} style={{padding:8,borderRadius:8,backgroundColor:selected?'rgba(254,243,199,.2)':C.white05,opacity:disabled?.2:1}}><Svg width={16} height={16} viewBox="0 0 24 24"><Path d={path} fill="none" stroke={selected?C.amber100:C.white40} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"/></Svg></Pressable>;
 return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,paddingLeft:8}}><View style={{gap:2}}><Text style={{fontSize:10,textTransform:'uppercase',letterSpacing:1,color:C.amber200,opacity:.5}}>{branch?'Variation':'Main Line'}</Text><Text style={{fontSize:9,color:C.white30,fontVariant:['tabular-nums']}}>Move {node.moveNumber} / {end.moveNumber}</Text></View><View style={{flexDirection:'row',gap:4}}>{icon('Start','M19 20 9 12 19 4Z M5 19V5',()=>onNav('start'))}{icon('Previous','M15 18 9 12 15 6',()=>onNav('prev'))}{icon('Next','M9 18 15 12 9 6',()=>onNav('next'))}{icon('End','M5 4 15 12 5 20Z M19 5V19',()=>onNav('end'))}</View><View style={{flexDirection:'row',gap:8,alignItems:'center'}}><Pressable disabled={!canToggle} onPress={()=>{const next=branch?branch.parent?.children[0]:node.children[1];if(next)onNode(next);}} style={{paddingHorizontal:12,paddingVertical:6,borderRadius:8,borderWidth:1,borderColor:canToggle?'rgba(253,230,138,.2)':C.white05,backgroundColor:canToggle?'rgba(254,243,199,.1)':C.white05,opacity:canToggle?1:.2}}><Text style={{fontSize:10,fontWeight:'700',textTransform:'uppercase',letterSpacing:.5,color:C.amber100}}>{branch?'Main':'Variation'}</Text></Pressable>{icon('Commentary','M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2Z',onComment,!node.properties.C,commentVisible)}</View></View>;
}
