import React from 'react';
import {Modal,StyleSheet,useWindowDimensions} from 'react-native';
import {View,Text,Pressable,ScrollView,AnimatedView} from '../ui';
import {ZoomIn} from 'react-native-reanimated';
import {DetailedScores,Player,GameState,ScoreEntry} from '../types';
import {C,SERIF} from '../theme';
type Props={scores:DetailedScores;ruleset:GameState['ruleset'];player:Player|null;results:boolean;winner:GameState['winner'];reason:GameState['winReason'];onClose:()=>void;onNewGame:()=>void};
export default function ScoreModal(p:Props){
 const {width}=useWindowDimensions();const visible=p.results||!!p.player;
 const row=(label:string,value:number,negative=false)=><View key={label} style={s.row}><Text style={[s.label,negative&&{color:'#f87171'}]}>{label}</Text><Text style={[s.value,negative&&{color:'#f87171'}]}>{negative?'-':'+'}{value}</Text></View>;
 const details=(c:Player,result:boolean)=>{const d=p.scores[c];return <>{row(result?'Territory':'Territory Controlled',d.territory)}{row(p.ruleset==='japanese'?(result?'Prisoners':'Prisoners Captured'):(result?'Stones':'Stones on Board'),p.ruleset==='japanese'?d.captures:d.stones)}{(result?c==='white':d.komi>0)&&row(result?'Komi':'Komi (Compensation)',d.komi)}{(result?c==='black':d.reverseKomi>0)&&row(result?'Comp.':'Reverse Komi',d.reverseKomi)}{d.penalties>0&&row('Time Penalties',d.penalties,true)}<View style={[s.row,s.total]}><Text style={s.totalLabel}>{result?'Total':'Total Score'}</Text><Text style={s.totalValue}>{d.total.toFixed(1)}</Text></View></>;};
 const title=p.results?p.winner==='draw'?`Draw${p.reason==='no-result'?' — no result':' — jigo'}`:'Match Conclusion':`${p.player==='black'?'Black':'White'} Score Details`;
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={p.onClose}><View style={s.overlay}><Pressable accessibilityLabel="Close score" style={StyleSheet.absoluteFill} onPress={p.onClose}/><AnimatedView entering={ZoomIn.duration(300)} style={[s.panel,{maxWidth:p.results?672:384}]}><View style={s.header}><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{p.ruleset.toUpperCase()} RULES</Text></View><ScrollView style={{maxHeight:600}} contentContainerStyle={[s.content,p.results&&{flexDirection:width>=768?'row':'column'}]}>{p.results?(['black','white'] as const).map(c=><View key={c} style={[s.card,p.winner===c?s.winning:s.losing]}><View style={s.cardHead}><View style={{width:10,height:10,borderRadius:5,backgroundColor:c==='black'?'#000':'#fff',borderWidth:1,borderColor:C.white20}}/><Text style={s.name}>{c}</Text>{p.winner===c&&<Text style={s.badge}>Winner ({p.reason==='time'?'Time':p.reason==='resign'?'Resign':'Points'})</Text>}</View>{details(c,true)}</View>):p.player&&details(p.player,false)}</ScrollView><View style={s.footer}>{p.results&&<Pressable onPress={p.onNewGame} style={[s.button,s.newGame]}><Text style={s.newLabel}>New Game</Text></Pressable>}<Pressable onPress={p.onClose} style={s.button}><Text style={s.closeLabel}>{p.results?'Return to Board':'Close'}</Text></Pressable></View></AnimatedView></View></Modal>;
}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(0,0,0,.60)',justifyContent:'center',alignItems:'center',paddingHorizontal:'5%'},panel:{width:'100%',backgroundColor:'#151515',borderWidth:1,borderColor:C.white10,borderRadius:16,overflow:'hidden'},header:{padding:16,borderBottomWidth:1,borderBottomColor:C.white05,backgroundColor:'rgba(255,255,255,.02)',alignItems:'center'},title:{fontFamily:SERIF,fontSize:20,color:C.amber50,letterSpacing:.5},subtitle:{fontSize:9,color:C.white30,letterSpacing:2,marginTop:4},content:{padding:16,gap:16},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:8},label:{fontSize:11,color:C.white30},value:{fontSize:11,color:C.amber100,fontVariant:['tabular-nums']},total:{paddingTop:12,marginTop:4,borderTopWidth:1,borderTopColor:C.white05},totalLabel:{fontFamily:SERIF,fontSize:9,color:C.white20,textTransform:'uppercase'},totalValue:{fontSize:24,color:C.amber50,fontVariant:['tabular-nums']},card:{flexGrow:1,padding:16,borderWidth:1,borderRadius:16},winning:{backgroundColor:'rgba(254,243,199,.03)',borderColor:'rgba(253,230,138,.20)'},losing:{backgroundColor:'rgba(0,0,0,.20)',borderColor:C.white05,opacity:.6},cardHead:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:16},name:{fontFamily:SERIF,fontSize:12,color:C.white40,textTransform:'uppercase',letterSpacing:1},badge:{marginLeft:'auto',fontSize:8,color:C.amber200,backgroundColor:'rgba(253,230,138,.10)',paddingHorizontal:8,paddingVertical:2,textTransform:'uppercase'},footer:{padding:16,paddingHorizontal:24,backgroundColor:'rgba(0,0,0,.20)',flexDirection:'row',gap:16},button:{flex:1,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor:C.white10,alignItems:'center'},newGame:{backgroundColor:'rgba(254,243,199,.10)',borderColor:'rgba(253,230,138,.20)'},newLabel:{fontSize:10,fontWeight:'700',color:C.amber100,letterSpacing:1,textTransform:'uppercase'},closeLabel:{fontSize:10,color:C.white30,letterSpacing:1,textTransform:'uppercase'}});
