import React from 'react';
import {Modal,StyleSheet} from 'react-native';
import {View,Text,Pressable,ScrollView} from '../ui';
import {Player,PlayerClock,TimeSettings,GamePhase} from '../types';
import {C,SERIF} from '../theme';
type Props={visible:boolean;clocks:Record<Player,PlayerClock>;settings:TimeSettings;active:Player;phase:GamePhase;onClose:()=>void};
// The reference's mobile Official Time panel, with live clock props.
export default function TimerPanel(p:Props){
 const format=(ms:number,precise=false)=>{ms=Math.max(0,ms);const total=Math.ceil(ms/1000),m=String(Math.floor(total/60)).padStart(2,'0'),s=String(total%60).padStart(2,'0');return `${m}:${s}${precise&&total<10?'.'+Math.floor((ms%1000)/100):''}`;};
 const clock=(player:Player)=>{const c=p.clocks[player],t=p.settings,active=p.active===player&&p.phase==='play';let display=format(c.mainTimeLeft,active&&c.mainTimeLeft<10000),sub='',period='',color='#fff';
 if(c.isInOvertime){color=C.amber200;if(t.system==='japanese'){display=format(c.byoyomiTimeLeft,true);sub='Overtime Activated';period=`${c.byoyomiPeriodsLeft}/${t.byoyomiPeriods||0}`;}else if(t.system==='canadian'){display=format(c.canadianTimeLeft,true);sub=`${c.canadianMovesLeft} stones remaining`;}else if(t.system==='nhk'){display=format(c.nhkTimeLeft,true);sub=`${c.nhkPeriodsLeft} periods remaining`;period=`${c.nhkPeriodsLeft}/${t.nhkPeriods||10}`;}}
 if(t.system==='ing'){const used=(t.ingPeriods||3)-c.ingPeriodsLeft;if(used>0){sub=`${used} penalty period${used>1?'s':''} used (-${used*2} pts)`;color=C.amber200;}}
 return <View key={player} style={[s.clock,active?{backgroundColor:C.white10,borderColor:C.white30,transform:[{scale:1.05}]}:{opacity:.6}]}><View style={s.nameRow}><View style={{width:12,height:12,borderRadius:6,backgroundColor:player==='black'?'#000':'#fff',borderWidth:1,borderColor:C.white30}}/><Text style={s.name}>{player}</Text></View><View style={{flexDirection:'row',alignItems:'baseline',gap:12}}><Text style={[s.digits,{color:active&&c.mainTimeLeft<30000&&!c.isInOvertime?'#f87171':color}]}>{display}</Text>{!!period&&<Text style={{fontFamily:SERIF,fontSize:24,color,opacity:.4}}>{period}</Text>}</View><View style={{height:16,marginTop:8}}><Text style={s.sub}>{sub}</Text></View></View>;
 };
 const t=p.settings,caption=t.system==='absolute'?'Sudden Death':t.system==='japanese'?`Japanese Byoyomi (${t.byoyomiSeconds}s x ${t.byoyomiPeriods})`:t.system==='canadian'?`Canadian Byoyomi (${t.canadianStones}/${t.canadianMinutes}m)`:t.system==='fischer'?`Fischer (+${t.fischerIncrement}s)`:t.system==='ing'?`Ing Rules (${t.ingPeriods}x penalty periods)`:`NHK Cup (${t.nhkSeconds}s + ${t.nhkPeriods} periods)`;
 return <Modal visible={p.visible} transparent animationType="fade" onRequestClose={p.onClose}><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={p.onClose}/><View style={s.panel}><View style={s.header}><View style={{width:10,height:10,borderRadius:5,backgroundColor:p.phase==='play'?'#10b981':C.white20}}/><Text style={s.title}>Official Time</Text><Pressable accessibilityLabel="Close Official Time" onPress={p.onClose} style={{marginLeft:'auto'}}><Text style={{fontSize:24,color:C.white40}}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.content}>{clock('black')}<View style={{height:1,width:'100%',backgroundColor:C.white10}}/>{clock('white')}</ScrollView><Text style={s.caption}>{caption}</Text></View></View></Modal>;
}
const s=StyleSheet.create({overlay:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'rgba(0,0,0,.6)',padding:20},panel:{width:'100%',maxWidth:480,maxHeight:'90%',backgroundColor:'#151515',borderRadius:24,borderWidth:1,borderColor:C.white05,overflow:'hidden',paddingBottom:32},header:{flexDirection:'row',alignItems:'center',gap:12,padding:16,borderBottomWidth:1,borderBottomColor:C.white05},title:{fontSize:10,fontWeight:'700',letterSpacing:3,textTransform:'uppercase',color:C.amber100},content:{padding:24,gap:32,alignItems:'center'},clock:{padding:24,borderWidth:1,borderColor:C.white05,borderRadius:16,alignItems:'center',width:'100%'},nameRow:{flexDirection:'row',gap:12,alignItems:'center',marginBottom:8},name:{fontFamily:SERIF,fontSize:12,letterSpacing:2.4,textTransform:'uppercase',color:C.white40},digits:{fontSize:48,letterSpacing:-2.4,fontVariant:['tabular-nums']},sub:{fontSize:10,letterSpacing:1,textTransform:'uppercase',color:C.amber100,opacity:.6},caption:{padding:16,fontFamily:SERIF,fontSize:9,letterSpacing:1,textAlign:'center',textTransform:'uppercase',color:C.white20}});
